"""Lingxing ERP OpenAPI integration core.

The package has no environment-file dependency. Credentials and persistent
token storage are injected by the application so production deployments can
use an OS or managed secret store.
"""

from .auth import (
    CredentialProvider,
    FileInterProcessLock,
    InterProcessLock,
    IssuedToken,
    LingxingCredentials,
    MemoryTokenStore,
    NullInterProcessLock,
    StaticCredentialProvider,
    TokenBundle,
    TokenEndpoint,
    TokenManager,
    TokenStore,
)
from .client import (
    APIResponse,
    BinaryResponse,
    DEFAULT_BASE_URL,
    ENDPOINTS,
    EndpointPolicy,
    LingxingClient,
    LingxingOpenAPIClient,
    LingxingTokenEndpoint,
    OperationKind,
    ResponseKind,
)
from .errors import (
    LingxingAPIError,
    LingxingAmbiguousWriteError,
    LingxingAuthError,
    LingxingConfigurationError,
    LingxingError,
    LingxingHTTPError,
    LingxingProtocolError,
    LingxingTransportError,
    redact_sensitive_text,
)
from .signing import (
    LingxingSigner,
    SignatureDetails,
    canonical_json_bytes,
    canonicalize_params,
)
from .runtime import (
    ConfigurationCredentialProvider,
    DEFAULT_LOCAL_TOKEN_LOCK_PATH,
    DEFAULT_LOCAL_TOKEN_PATH,
    DpapiTokenStore,
    EncryptedConfigurationCredentialProvider,
    LOCAL_TOKEN_ENVELOPE_FORMAT,
    LOCAL_TOKEN_ENVELOPE_VERSION,
    LOCAL_TOKEN_PURPOSE,
    LocalEncryptedTokenStore,
    create_lingxing_openapi_client,
    default_local_state_directory,
)

__all__ = [
    "APIResponse",
    "BinaryResponse",
    "CredentialProvider",
    "ConfigurationCredentialProvider",
    "DEFAULT_BASE_URL",
    "DEFAULT_LOCAL_TOKEN_LOCK_PATH",
    "DEFAULT_LOCAL_TOKEN_PATH",
    "ENDPOINTS",
    "EndpointPolicy",
    "EncryptedConfigurationCredentialProvider",
    "FileInterProcessLock",
    "InterProcessLock",
    "IssuedToken",
    "LingxingAPIError",
    "LingxingAmbiguousWriteError",
    "LingxingAuthError",
    "LingxingClient",
    "LingxingConfigurationError",
    "LingxingCredentials",
    "LingxingError",
    "LingxingHTTPError",
    "LingxingOpenAPIClient",
    "LingxingProtocolError",
    "LingxingSigner",
    "LingxingTokenEndpoint",
    "LingxingTransportError",
    "LOCAL_TOKEN_ENVELOPE_FORMAT",
    "LOCAL_TOKEN_ENVELOPE_VERSION",
    "LOCAL_TOKEN_PURPOSE",
    "LocalEncryptedTokenStore",
    "MemoryTokenStore",
    "NullInterProcessLock",
    "OperationKind",
    "ResponseKind",
    "SignatureDetails",
    "StaticCredentialProvider",
    "TokenBundle",
    "TokenEndpoint",
    "TokenManager",
    "TokenStore",
    "DpapiTokenStore",
    "canonical_json_bytes",
    "canonicalize_params",
    "create_lingxing_openapi_client",
    "default_local_state_directory",
    "redact_sensitive_text",
]
