"""ERP 自动化应用服务。"""

from .capabilities import (
    Capability,
    CapabilityMode,
    CapabilityRouter,
    ManualReviewRequired,
    MutationResult,
    MutationState,
)
from .rollback import RollbackManager, SCRIPT_BASELINE_BRANCH
from .desktop_tasks import CustomOrderOperationsFactory, DesktopTaskRunner, TaskExecutionResult
from .custom_order_api import CustomOrderApiPlanError, LingxingCustomOrderApiOperations
from .desktop_services import DesktopApiServices, build_capability_router
from .notification_contact_refresh import (
    ContactRefreshItem,
    ContactRefreshSummary,
    refresh_shipment_notification_contacts,
)
from .api_scanners import (
    ApiPageTrace,
    ApiScanDiagnostic,
    ApiScanState,
    CustomizationApiScanResult,
    MissingFieldNotice,
    NormalizedOrderRows,
    OrderPaginationResult,
    ShipmentApiScanResult,
    fetch_all_order_pages,
    normalize_api_order_rows,
    redact_sensitive_payload,
    redact_sensitive_text,
    receiver_email_from_payload,
    receiver_phone_from_payload,
    scan_customization_candidates,
    scan_shipment_candidates,
)
from .lingxing_gateway import (
    AttachmentData,
    FAST_OUTBOUND_FAILED,
    FAST_OUTBOUND_RESULT_STATE_KEY,
    FAST_OUTBOUND_SUCCEEDED,
    LingxingGateway,
    LookupRecord,
    MutationVerification,
    OrderDetail,
    OrderPage,
    OrderRecord,
    PageResult,
    VerificationHook,
    VerificationOutcome,
)
from .api_erp_mark import (
    ApiErpMarkAdapter,
    ErpLogisticsRoute,
    ManagedApiErpMarkFunc,
    OutboundStrategy,
    routes_from_configuration,
)

__all__ = [
    "ApiPageTrace",
    "ApiErpMarkAdapter",
    "ApiScanDiagnostic",
    "ApiScanState",
    "Capability",
    "CapabilityMode",
    "CapabilityRouter",
    "AttachmentData",
    "CustomizationApiScanResult",
    "ContactRefreshItem",
    "ContactRefreshSummary",
    "CustomOrderApiPlanError",
    "CustomOrderOperationsFactory",
    "DesktopTaskRunner",
    "ErpLogisticsRoute",
    "FAST_OUTBOUND_FAILED",
    "FAST_OUTBOUND_RESULT_STATE_KEY",
    "FAST_OUTBOUND_SUCCEEDED",
    "DesktopApiServices",
    "LingxingGateway",
    "LingxingCustomOrderApiOperations",
    "LookupRecord",
    "ManagedApiErpMarkFunc",
    "ManualReviewRequired",
    "MutationResult",
    "MutationState",
    "MutationVerification",
    "MissingFieldNotice",
    "NormalizedOrderRows",
    "OrderDetail",
    "OrderPage",
    "OrderRecord",
    "OutboundStrategy",
    "OrderPaginationResult",
    "PageResult",
    "RollbackManager",
    "SCRIPT_BASELINE_BRANCH",
    "ShipmentApiScanResult",
    "TaskExecutionResult",
    "build_capability_router",
    "VerificationHook",
    "VerificationOutcome",
    "fetch_all_order_pages",
    "normalize_api_order_rows",
    "redact_sensitive_payload",
    "redact_sensitive_text",
    "receiver_email_from_payload",
    "receiver_phone_from_payload",
    "routes_from_configuration",
    "refresh_shipment_notification_contacts",
    "scan_customization_candidates",
    "scan_shipment_candidates",
]
